service: search-index-service

frameworkVersion: '>=1.0.0 <2.0.0'

package:
  exclude:
    - tests/**
    - docs/**
    - scripts/**

provider:
  name: aws
  region: us-west-2
  runtime: nodejs8.10
  stage: dev
  role: arn:aws:iam::003849295229:role/${opt:stage, self:provider.stage}-search-index-service
  deploymentBucket: accordo.builds
  versionFunctions: false
  vpc:
    securityGroupIds:
      - ${env:${opt:stage, self:provider.stage}_security_group_id}
    subnetIds:
      - ${env:${opt:stage, self:provider.stage}_subnet_id_1}
      - ${env:${opt:stage, self:provider.stage}_subnet_id_2}

custom:
  authorizerName: accordo-authorizer
  stageDescription: 'repo: search-index-service, build: ${env:GIT_TAG}, branch: ${env:GIT_BRANCH}, commit: ${env:GIT_COMMIT}'
  customDomain:
    domainName: ${env:${opt:stage, self:provider.stage}_domain_name}
    basePath: 'search-index'
    stage: ${opt:stage, self:provider.stage}
    createRoute53Record: false

functions:
  search-index-service:
    handler: src/index.handler
    name: ${opt:stage, self:provider.stage}-search-index-service
    memorySize: 512
    timeout: 15
    reservedConcurrency: ${env:LambdaReservedConcurrency}
    environment:
      # only need to add stage here, all variables will be pulled from secret manager using the stage
      # and picked using names in config.json
      stage: ${opt:stage, self:provider.stage}
      sqsHealthCheckNormal: 200
      sqsHealthCheckWarning: 500
    description: 'repo: search-index-service, build: ${env:GIT_TAG}, branch: ${env:GIT_BRANCH}, commit: ${env:GIT_COMMIT}'
    events:
      - http:
          path: health
          method: get
          cors: true
          authorizer: arn:aws:lambda:us-west-2:003849295229:function:accordo-authorizer
      - schedule:
          name: ${opt:stage, self:provider.stage}-backfill-office365-batch
          description: 'Backfill batches of organizations Office 365 data on ${opt:stage, self:provider.stage}.'
          rate: ${env:${opt:stage, self:provider.stage}_OFFICE365_BACKFILL_BATCH_RATE}
          enabled: true
          input: '{"action": "OFFICE365_BACKFILL_BATCH"}'

    deadLetter:
      targetArn: arn:aws:sqs:us-west-2:003849295229:${opt:stage, self:provider.stage}-search-index-service-dlq

plugins:
  - serverless-plugin-include-dependencies
  - serverless-domain-manager
  - set-accordo-resources
  - serverless-plugin-lambda-dead-letter
